org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStore=/etc/ssl/certs/java/cacerts -Djavax.net.ssl.trustStorePassword=changeit
systemProp.fabric.loom.dontCheckCertificates=true
fabric.loom.dontCheckCertificates=true
org.gradle.daemon=false

minecraft_version=26.2
archives_base_name=life_xp_challenge
mod_version=1.6.1
maven_group=com.hs1n

architectury_loom_version=1.17-SNAPSHOT
architectury_plugin_version=3.5-SNAPSHOT
asm_version=9.8

loader_version=0.19.5
fabric_version=0.160.0+26.2
fabric_loader_version=0.19.5
fabric_api_version=0.160.0+26.2

architectury_version=21.1.9
neoforge_version=26.2.0.88

yacl_version=3.9.6+26.2
modmenu_version=20.0.2
jei_version=30.32.0.215
emi_version=1.1.24+1.21.1
